upstream forum-api {
    server localhost:3000;
}

server {
    listen 80;
    listen 443 ssl;

    location /threads {
        limit_req zone=one rate=90r/m;
        proxy_pass http://forum-api;
    }

    location / {
        proxy_pass http://forum-api;
    }
}